stages:
  prepare_data:
    cmd: python src/data.py
    deps:
      - src/data.py
      - params.yaml
    outs:
      - data/processed/
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - src/model.py
      - src/config.py
      - data/processed/
      - params.yaml
    outs:
      - models/
      - mlruns/
  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/
      - data/processed/
      - params.yaml
    outs:
      - reports/