data:
  test_size: 0.2
  random_state: 42

models:
  random_forest:
    estimator: RandomForestClassifier
    param_grid:
      n_estimators: [50, 100, 200]
      max_depth: [5, 10, null]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 4]
  gradient_boosting:
    estimator: GradientBoostingClassifier
    param_grid:
      n_estimators: [100]
      max_depth: [3, 5]
  logistic_regression:
    estimator: LogisticRegression
    param_grid:
      max_iter: [1000]
  svm:
    estimator: SVC
    param_grid:
      probability: [true]
      max_iter: [1000]